class AppLocalization {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'select_user': 'Who are you?',
      'home': 'Home',
      'phrases_lessons': 'Phrases & Lessons',
      'kisses_hugs': 'Kisses & Hugs',
      'bucket_list': 'Bucket List',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'normal': 'Normal',
      'germany': 'Germany',
      'mexico': 'Mexico',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'english': 'English',
      'spanish': 'Español',
      'german': 'Deutsch',
      'change_profile': 'Change profile',
      'full_reset': 'Full Reset',
    },
    'es': {
      'select_user': '¿Quién eres?',
      'home': 'Inicio',
      'phrases_lessons': 'Frases y Lecciones',
      'kisses_hugs': 'Besos y Abrazos',
      'bucket_list': 'Lista de Deseos',
      'settings': 'Configuración',
      'theme': 'Tema',
      'language': 'Idioma',
      'normal': 'Normal',
      'germany': 'Alemania',
      'mexico': 'México',
      'notifications': 'Notificaciones',
      'logout': 'Cerrar sesión',
      'cancel': 'Cancelar',
      'english': 'English',
      'spanish': 'Español',
      'german': 'Deutsch',
      'change_profile': 'Cambiar perfil',
      'full_reset': 'Reiniciar completamente',
    },
    'de': {
      'select_user': 'Wer bist du?',
      'home': 'Startseite',
      'phrases_lessons': 'Phrasen und Lektionen',
      'kisses_hugs': 'Küsse und Umarmungen',
      'bucket_list': 'Wunschliste',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Sprache',
      'normal': 'Normal',
      'germany': 'Deutschland',
      'mexico': 'Mexiko',
      'notifications': 'Benachrichtigungen',
      'logout': 'Abmelden',
      'cancel': 'Abbrechen',
      'english': 'English',
      'spanish': 'Español',
      'german': 'Deutsch',
      'change_profile': 'Profil wechseln',
      'full_reset': 'Vollständiger Neustart',
    },
  };

  static String translate(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}